version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./ap-gateway  # Directorio del código del API Gateway
    ports:
      - "5000:5000"  # Exponer el API Gateway en el puerto 5000
    depends_on:
      - flight-search
      - user-management
    networks:
      - app-network
    environment:
      - FLIGHT_SEARCH_SERVICE=http://flight-search:5001
      - USER_MANAGEMENT_SERVICE=http://user-management:5003

  flight-search:
    container_name: flight-search
    build:
      context: ./flight-search
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://flight-search-db:27017/flightsearchdb
    depends_on:
      - flight-search-db
    networks:
      - app-network

  flight-search-db:
    image: mongo:6.0
    container_name: flight-search-db
    environment:
      MONGO_INITDB_DATABASE: FlightDB
    volumes:
      - ./flight-search/data_db:/data/db  # Mapeo a la ubicación en el host
    ports:
      - "27017:27017"  # Mapeo del puerto al host
    networks:
      - app-network

  user-management:
    container_name: user-management
    build:
      context: ./user-management
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://user-management-db:27019/usermanagementdb
    depends_on:
      - user-management-db
    networks:
      - app-network

  user-management-db:
    image: mongo:6.0
    container_name: user-management-db
    environment:
      MONGO_INITDB_DATABASE: UsersDB
    volumes:
      - ./user-management/data_db:/data/db  # Mapeo a la ubicación en el host
    ports:
      - "27019:27017"  # Mapeo del puerto al host
    networks:
      - app-network

volumes: {}
networks:
  app-network:
